root: true

extends:
  - "plugin:vue/vue3-essential"
  - "plugin:vue/vue3-strongly-recommended"
  - "plugin:vuejs-accessibility/recommended"
  - "eslint:recommended"
  - "@vue/eslint-config-typescript"
  - "@vue/eslint-config-prettier/skip-formatting"

plugins:
  - "vuejs-accessibility"

overrides:
  - files:
      - "**/__tests__/*.{cy,spec}.{js,ts,jsx,tsx}"
      - "cypress/e2e/**/*.{cy,spec}.{js,ts,jsx,tsx}"
    extends:
      - "plugin:cypress/recommended"

parserOptions:
  ecmaVersion: latest

rules:
  linebreak-style:
    - "error"
    - "unix"

  quotes:
    - "error"
    - "double"

  semi:
    - "error"
    - "always"

  complexity:
    - "error"
    - 9

  "default-case-last": "error"
  "consistent-return": off
  "array-callback-return": off
  "guard-for-in": off

  "prefer-destructuring":
    - "error"
    - object: true
      array: true

  "no-multiple-empty-lines": "error"
  "no-plusplus": off
  "no-shadow": off
  "no-use-before-define": off
  "no-restricted-syntax": off
  "no-continue": off
  "no-underscore-dangle": off
  "no-param-reassign": off
  "no-useless-constructor": off
  "no-empty-function": off

  "no-else-return":
    - "warn"
    - allowElseIf: true

  "no-console":
    - "warn"
    - allow:
        - "error"
        - "assert"
        - "warn"

  "vue/comma-dangle":
    - "warn"
    - "only-multiline"

  "vue/multi-word-component-names": off

  "vue/attributes-order":
    - "error"
    - order:
        - "LIST_RENDERING"
        - "CONDITIONALS"
        - "RENDER_MODIFIERS"
        - "UNIQUE"
        - "DEFINITION"
        - "TWO_WAY_BINDING"
        - "SLOT"
        - "GLOBAL"
        - "OTHER_DIRECTIVES"
        - "ATTR_DYNAMIC"
        - "ATTR_SHORTHAND_BOOL"
        - "ATTR_STATIC"
        - "EVENTS"
        - "CONTENT"
      alphabetical: false

  "@typescript-eslint/no-useless-constructor": "error"
  "@typescript-eslint/no-empty-function": "error"
  "@typescript-eslint/no-unused-vars": off
  "@typescript-eslint/quotes": off
  "@typescript-eslint/indent": off
  "@typescript-eslint/comma-dangle": off
  "@typescript-eslint/no-use-before-define": off

  "@typescript-eslint/consistent-type-imports":
    - "error"
    - prefer: "type-imports"
      fixStyle: "inline-type-imports"
