semi: true
singleQuote: false
printWidth: 80
tabWidth: 2
trailingComma: "es5"
bracketSpacing: true
arrowParens: "avoid"
bracketSameLine: true
vueIndentScriptAndStyle: true
htmlWhitespaceSensitivity: "ignore"
endOfLine: "lf"
