blank_issues_enabled: false
contact_links:
  - name: "Accessibility discussions"
    url: https://github.com/norahmaria/typeach/discussions/categories/accessibility
    about: "Discuss accessibility concerns that might not have a single or definite answer or fix"
  - name: "Ideas"
    url: https://github.com/norahmaria/typeach/discussions/categories/ideas
    about: "Suggest a new feature or discuss ideas"
