name: "Run Cypress Tests"

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/test.yml"
      - "cypress"
      - "src/**"
      - "cypress.config.js"
      - "env.d.ts"
      - "package-lock.json"
      - "package.json"
      - "tsconfig.*.json"
      - "tsconfig.json"
      - "vite.config.mts"

jobs:
  test:
    name: "Run component tests"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: "Run tests"
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true
          browser: "chrome"
          working-directory: ""
